//
//  TTPaintCodeTutorial.h
//  ProjectName
//
//  Created by AuthorName on 15/9/2.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface TTPaintCodeTutorial : NSObject

// Colors
+ (UIColor*)color;

// Drawing Methods
+ (void)drawStopwatch;
+ (void)drawPaintCodeTutorial;

@end
