//
//  TTStarCode.h
//  TonyTong
//
//  Created by TTName on 15/9/2.
//  Copyright (c) 2015 TTName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface TTStarCode : NSObject

// Drawing Methods
+ (void)drawTTPaint;

@end
