//
//  TTStarCode.m
//  TonyTong
//
//  Created by TTName on 15/9/2.
//  Copyright (c) 2015 TTName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "TTStarCode.h"


@implementation TTStarCode

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawTTPaint
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(10, 0)];
    [bezierPath addLineToPoint: CGPointMake(13.53, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(19.51, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(15.71, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(15.88, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(10, 16)];
    [bezierPath addLineToPoint: CGPointMake(4.12, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(4.29, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(0.49, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(6.47, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(10, 0)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(30, 0)];
    [bezierPath addLineToPoint: CGPointMake(33.53, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(39.51, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(35.71, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(35.88, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(30, 16)];
    [bezierPath addLineToPoint: CGPointMake(24.12, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(24.29, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(20.49, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(26.47, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(30, 0)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(50, 0)];
    [bezierPath addLineToPoint: CGPointMake(53.53, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(59.51, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(55.71, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(55.88, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(50, 16)];
    [bezierPath addLineToPoint: CGPointMake(44.12, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(44.29, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(40.49, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(46.47, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(50, 0)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(70, 0)];
    [bezierPath addLineToPoint: CGPointMake(73.53, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(79.51, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(75.71, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(75.88, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(70, 16)];
    [bezierPath addLineToPoint: CGPointMake(64.12, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(64.29, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(60.49, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(66.47, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(70, 0)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(90, 0)];
    [bezierPath addLineToPoint: CGPointMake(93.53, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(99.51, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(95.71, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(95.88, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(90, 16)];
    [bezierPath addLineToPoint: CGPointMake(84.12, 18.09)];
    [bezierPath addLineToPoint: CGPointMake(84.29, 11.85)];
    [bezierPath addLineToPoint: CGPointMake(80.49, 6.91)];
    [bezierPath addLineToPoint: CGPointMake(86.47, 5.15)];
    [bezierPath addLineToPoint: CGPointMake(90, 0)];
    [bezierPath closePath];
    [UIColor.redColor setFill];
    [bezierPath fill];
}

@end
